In [1]:
# a power b, can use both ^ and **
message ("2 ^ 3 is")
2 ^ 3
2 ** 3
# modulus operator is %%
message("5 % 2 is")
5 %% 2 # 5 % 2 gives error in R

2 ^ 3 is


[1] 8

[1] 8

5 % 2 is


[1] 1

In [2]:
n <- 2.2
i <- 5
t <- TRUE
f <- FALSE
char <- "Hello World!"
c <- 'Single Quote Char'
n
i
t
f
char
c
class(n)
class(i)
class(t)
class(f)
class(char)
class(c)

[1] 2.2

[1] 5

[1] TRUE

[1] FALSE

[1] "Hello World!"

[1] "Single Quote Char"

[1] "numeric"

[1] "numeric"

[1] "logical"

[1] "logical"

[1] "character"

[1] "character"

In [3]:
# vector can only take 1 datatype
temps <- c(72,71,70,79,69,66,70)

# 

In [4]:
temps

[1] 72 71 70 79 69 66 70

In [5]:
names(temps) <- c('Mon','Tue','Wed','Thu','Fri','Sat','Sun')
temps

Mon Tue Wed Thu Fri Sat Sun 
 72  71  70  79  69  66  70

In [6]:
days = c('Mon','Tue','Wed','Thu','Fri','Sat','Sun')

In [7]:
names(temps) <- days
temps

Mon Tue Wed Thu Fri Sat Sun 
 72  71  70  79  69  66  70

In [8]:
v1 <- c(1,2,3)
v2 <- c(4,3,2)

In [9]:
v1 + v2
v1 - v2
v1 * v2
v1 / v2

[1] 5 5 5

[1] -3 -1  1

[1] 4 6 6

[1] 0.2500000 0.6666667 1.5000000

In [10]:
sum.of.vec <- sum(v1)
sum.of.vec

[1] 6

In [11]:
# builtin functions in R
mean(v1)
sd(v1)
max(v1)
min(v1)
prod(v1)

[1] 2

[1] 1

[1] 3

[1] 1

[1] 6

In [12]:
v1 <- c(100,200,300)
v2 <- c('a','b','c')
v1[2]
v1[1:2]
v1[c(1,3)]

[1] 200

[1] 100 200

[1] 100 300

In [13]:
v <- c(1,2,3,4,5,6,7,8,9,10)
v
v[2:4]

[1]  1  2  3  4  5  6  7  8  9 10

[1] 2 3 4

In [14]:
v <- c(1,2,3,4)
names(v) <- c('a','b','c','d')
v[2]
v['b']
v[c('c','d','a')]

b 
2

b 
2

c d a 
3 4 1

In [15]:
v
v>2
v[v>2]
my.filter <- v>2
v[my.filter]

a b c d 
1 2 3 4

a     b     c     d 
FALSE FALSE  TRUE  TRUE

c d 
3 4

c d 
3 4

In [16]:
#help('vector')
#??vector
#help.search('vector')

In [17]:
5 > 6
5 < 6

[1] FALSE

[1] TRUE

In [18]:
5 == 6
2 != 4

[1] FALSE

[1] TRUE

In [19]:
v <- c(1,2,3,4,5)
v < 2
v == 3

[1]  TRUE FALSE FALSE FALSE FALSE

[1] FALSE FALSE  TRUE FALSE FALSE

In [20]:
v <- c(1,2,3,4,5)
v2 = c(10,20,30,40,50)
v < v2

[1] TRUE TRUE TRUE TRUE TRUE

In [21]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [22]:
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
matrix(v)

[,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10

In [24]:
matrix(v,nrow=2)
matrix(v,nrow=5)

[,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

In [25]:
matrix(1:12,byrow = FALSE,nrow=4)

[,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

In [26]:
matrix(1:12,byrow = T,nrow=4)

[,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12

In [27]:
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)
stocks <- c(goog,msft)
stocks

[1] 450 451 452 445 468 230 231 232 236 228

In [28]:
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=5)
stock.matrix
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)
stock.matrix

[,1] [,2]
[1,]  450  451
[2,]  452  445
[3,]  468  230
[4,]  231  232
[5,]  236  228

[,1] [,2] [,3] [,4] [,5]
[1,]  450  451  452  445  468
[2,]  230  231  232  236  228

In [29]:
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names
1 #this is a comment
"This is 1"
stock.matrix
2
colSums(stock.matrix)
3
rowSums(stock.matrix)
4
rowMeans(stock.matrix)
5
FB <- c(111,112,113,120,145)
FB
6
tech.stocks <- rbind(stock.matrix,FB)
tech.stocks
7 
avg <- rowMeans(tech.stocks)
avg


[1] 1

[1] "This is 1"

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

[1] 2

Mon Tue Wed Thu Fri 
680 682 684 681 696

[1] 3

GOOG MSFT 
2266 1157

[1] 4

GOOG  MSFT 
453.2 231.4

[1] 5

[1] 111 112 113 120 145

[1] 6

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228
FB   111 112 113 120 145

[1] 7

GOOG  MSFT    FB 
453.2 231.4 120.2

In [30]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30
[4,]   31   32   33   34   35   36   37   38   39    40
[5,]   41   42   43   44   45   46   47   48   49    50

In [31]:
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    2    4    6    8   10   12   14   16   18    20
[2,]   22   24   26   28   30   32   34   36   38    40
[3,]   42   44   46   48   50   52   54   56   58    60
[4,]   62   64   66   68   70   72   74   76   78    80
[5,]   82   84   86   88   90   92   94   96   98   100

In [32]:
1/mat

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
[2,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.06250000
[3,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000 0.03846154
[4,] 0.03225806 0.03125000 0.03030303 0.02941176 0.02857143 0.02777778
[5,] 0.02439024 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913
           [,7]       [,8]       [,9]      [,10]
[1,] 0.14285714 0.12500000 0.11111111 0.10000000
[2,] 0.05882353 0.05555556 0.05263158 0.05000000
[3,] 0.03703704 0.03571429 0.03448276 0.03333333
[4,] 0.02702703 0.02631579 0.02564103 0.02500000
[5,] 0.02127660 0.02083333 0.02040816 0.02000000

In [33]:
mat/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5    1  1.5    2  2.5    3  3.5    4  4.5     5
[2,]  5.5    6  6.5    7  7.5    8  8.5    9  9.5    10
[3,] 10.5   11 11.5   12 12.5   13 13.5   14 14.5    15
[4,] 15.5   16 16.5   17 17.5   18 18.5   19 19.5    20
[5,] 20.5   21 21.5   22 22.5   23 23.5   24 24.5    25

In [34]:
mat ^ 2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81   100
[2,]  121  144  169  196  225  256  289  324  361   400
[3,]  441  484  529  576  625  676  729  784  841   900
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521  1600
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401  2500

In [35]:
mat > 17

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [36]:
matrix(mat [mat > 17], nrow = 4)

Warning message:
In matrix(mat[mat > 17], nrow = 4): data length [33] is not a sub-multiple or multiple of the number of rows [4]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
[1,]   21   32   43   25   36   47   48   49   50
[2,]   31   42   24   35   46   18   19   20   21
[3,]   41   23   34   45   27   28   29   30   31
[4,]   22   33   44   26   37   38   39   40   41

In [37]:
mat + mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    2    4    6    8   10   12   14   16   18    20
[2,]   22   24   26   28   30   32   34   36   38    40
[3,]   42   44   46   48   50   52   54   56   58    60
[4,]   62   64   66   68   70   72   74   76   78    80
[5,]   82   84   86   88   90   92   94   96   98   100

In [38]:
mat/mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    1    1    1    1    1    1    1    1     1
[2,]    1    1    1    1    1    1    1    1    1     1
[3,]    1    1    1    1    1    1    1    1    1     1
[4,]    1    1    1    1    1    1    1    1    1     1
[5,]    1    1    1    1    1    1    1    1    1     1

In [39]:
mat2 <- matrix(1:9, nrow=3)
mat2 * mat2
mat2 %*% mat2

[,1] [,2] [,3]
[1,]    1   16   49
[2,]    4   25   64
[3,]    9   36   81

[,1] [,2] [,3]
[1,]   30   66  102
[2,]   36   81  126
[3,]   42   96  150

In [40]:
data()

Data sets in package 'datasets':

AirPassengers           Monthly Airline Passenger Numbers 1949-1960
BJsales                 Sales Data with Leading Indicator
BJsales.lead (BJsales)
                        Sales Data with Leading Indicator
BOD                     Biochemical Oxygen Demand
CO2                     Carbon Dioxide Uptake in Grass Plants
ChickWeight             Weight versus age of chicks on different diets
DNase                   Elisa assay of DNase
EuStockMarkets          Daily Closing Prices of Major European Stock
                        Indices, 1991-1998
Formaldehyde            Determination of Formaldehyde
HairEyeColor            Hair and Eye Color of Statistics Students
Harman23.cor            Harman Example 2.3
Harman74.cor            Harman Example 7.4
Indometh                Pharmacokinetics of Indomethacin
InsectSprays            Effectiveness of Insect Sprays
JohnsonJohnson          Quarterly Earnings per Johnson & Johnson Share
LakeHuron               Level of Lake Huron 1875-1972
LifeCycleSavings        Intercountry Life-Cycle Savings Data
Loblolly                Growth of Loblolly pine trees
Nile                    Flow of the River Nile
Orange                  Growth of Orange Trees
OrchardSprays           Potency of Orchard Sprays
PlantGrowth             Results from an Experiment on Plant Growth
Puromycin               Reaction Velocity of an Enzymatic Reaction
Seatbelts               Road Casualties in Great Britain 1969-84
Theoph                  Pharmacokinetics of Theophylline
Titanic                 Survival of passengers on the Titanic
ToothGrowth             The Effect of Vitamin C on Tooth Growth in
                        Guinea Pigs
UCBAdmissions           Student Admissions at UC Berkeley
UKDriverDeaths          Road Casualties in Great Britain 1969-84
UKgas                   UK Quarterly Gas Consumption
USAccDeaths             Accidental Deaths in the US 1973-1978
USArrests               Violent Crime Rates by US State
USJudgeRatings          Lawyers' Ratings of State Judges in the US
                        Superior Court
USPersonalExpenditure   Personal Expenditure Data
UScitiesD               Distances Between European Cities and Between
                        US Cities
VADeaths                Death Rates in Virginia (1940)
WWWusage                Internet Usage per Minute
WorldPhones             The World's Telephones
ability.cov             Ability and Intelligence Tests
airmiles                Passenger Miles on Commercial US Airlines,
                        1937-1960
airquality              New York Air Quality Measurements
anscombe                Anscombe's Quartet of 'Identical' Simple Linear
                        Regressions
attenu                  The Joyner-Boore Attenuation Data
attitude                The Chatterjee-Price Attitude Data
austres                 Quarterly Time Series of the Number of
                        Australian Residents
beaver1 (beavers)       Body Temperature Series of Two Beavers
beaver2 (beavers)       Body Temperature Series of Two Beavers
cars                    Speed and Stopping Distances of Cars
chickwts                Chicken Weights by Feed Type
co2                     Mauna Loa Atmospheric CO2 Concentration
crimtab                 Student's 3000 Criminals Data
discoveries             Yearly Numbers of Important Discoveries
esoph                   Smoking, Alcohol and (O)esophageal Cancer
euro                    Conversion Rates of Euro Currencies
euro.cross (euro)       Conversion Rates of Euro Currencies
eurodist                Distances Between European Cities and Between
                        US Cities
faithful                Old Faithful Geyser Data
fdeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
freeny                  Freeny's Revenue Data
freeny.x (freeny)       Freeny's Revenue Data
freeny.y (freeny)       Freeny's Revenue Data
infert                  Infertility after Spontaneous

In [41]:
states <- state.x77
head(states,3)
tail(states,3)

Population Income Illiteracy Life Exp Murder HS Grad Frost   Area
Alabama       3615   3624        2.1    69.05   15.1    41.3    20  50708
Alaska         365   6315        1.5    69.31   11.3    66.7   152 566432
Arizona       2212   4530        1.8    70.55    7.8    58.1    15 113417

Population Income Illiteracy Life Exp Murder HS Grad Frost  Area
West Virginia       1799   3617        1.4    69.48    6.7    41.6   100 24070
Wisconsin           4589   4468        0.7    72.48    3.0    54.5   149 54464
Wyoming              376   4566        0.6    70.29    6.9    62.9   173 97203

In [42]:
summary(states)

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81163  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [43]:
days <- c('mon','tue','wed','thu','fri')
temp <- c(22.2,21,23,24.3,25)
rain <- c(TRUE, TRUE, FALSE, FALSE, TRUE)
df <- data.frame(days,temp,rain)
df
df[c(1,3,5),c('days','rain')]
df$rain
df['rain']
subset(df,subset= temp>23 & rain ==T)
subset(df,subset= rain==T)

days temp  rain
1  mon 22.2  TRUE
2  tue 21.0  TRUE
3  wed 23.0 FALSE
4  thu 24.3 FALSE
5  fri 25.0  TRUE

days  rain
1  mon  TRUE
3  wed FALSE
5  fri  TRUE

[1]  TRUE  TRUE FALSE FALSE  TRUE

rain
1  TRUE
2  TRUE
3 FALSE
4 FALSE
5  TRUE

days temp rain
5  fri   25 TRUE

days temp rain
1  mon 22.2 TRUE
2  tue 21.0 TRUE
5  fri 25.0 TRUE

In [44]:
# check structure and summary
str(df)
summary(df)

'data.frame':	5 obs. of  3 variables:
 $ days: Factor w/ 5 levels "fri","mon","thu",..: 2 4 5 3 1
 $ temp: num  22.2 21 23 24.3 25
 $ rain: logi  TRUE TRUE FALSE FALSE TRUE


  days        temp         rain        
 fri:1   Min.   :21.0   Mode :logical  
 mon:1   1st Qu.:22.2   FALSE:2        
 thu:1   Median :23.0   TRUE :3        
 tue:1   Mean   :23.1   NA's :0        
 wed:1   3rd Qu.:24.3                  
         Max.   :25.0                  

In [45]:
sorted.temp <- order(df['temp'])
df[sorted.temp,] #note the , after sorted.temp
desc.temp <- order(-df$temp)  
df[desc.temp,]

days temp  rain
2  tue 21.0  TRUE
1  mon 22.2  TRUE
3  wed 23.0 FALSE
4  thu 24.3 FALSE
5  fri 25.0  TRUE

days temp  rain
5  fri 25.0  TRUE
4  thu 24.3 FALSE
3  wed 23.0 FALSE
1  mon 22.2  TRUE
2  tue 21.0  TRUE

In [46]:
empty <- data.frame() # empty data frame
empty

data frame with 0 columns and 0 rows

In [47]:
c1 <- 1:3 # vector of integers
c2 <- letters[1:3] # vector of strings
df <- data.frame(col.name.1=c1,col.name.2=c2)
df
nrow(df)
ncol(df)
colnames(df)
rownames(df)

col.name.1 col.name.2
1          1          a
2          2          b
3          3          c

[1] 3

[1] 2

[1] "col.name.1" "col.name.2"

[1] "1" "2" "3"

In [48]:
df[1, ]
as.numeric(as.vector(df[1,]))

col.name.1 col.name.2
1          1          a

[1] 1 1

In [49]:
cars <- mtcars
head(cars)

mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1

In [50]:
colv1 <- cars$mpg # returns a vector
colv1
colv2 <- cars[, 'mpg'] # returns vector
colv2
colv3<- cars[, 1] # a is int or string
colv3
colv4 <- cars[['mpg']] # returns a vector
colv4

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [51]:
df2 <- data.frame(col.name.1=2000,col.name.2='new' )
df2
df
dfnew <- rbind(df,df2)
dfnew

col.name.1 col.name.2
1       2000        new

col.name.1 col.name.2
1          1          a
2          2          b
3          3          c

col.name.1 col.name.2
1          1          a
2          2          b
3          3          c
4       2000        new

In [52]:
df[['col1.times.2']] <- df$col.name.1 * 2
df

col.name.1 col.name.2 col1.times.2
1          1          a            2
2          2          b            4
3          3          c            6

In [53]:
df[, 'copy.of.col2'] <- df$col.name.2 # copy a col
df

col.name.1 col.name.2 col1.times.2 copy.of.col2
1          1          a            2            a
2          2          b            4            b
3          3          c            6            c

In [54]:
df3 <- cbind(df, df$col.name.1)
df3

col.name.1 col.name.2 col1.times.2 copy.of.col2 df$col.name.1
1          1          a            2            a             1
2          2          b            4            b             2
3          3          c            6            c             3

In [55]:
colnames(df)[2] <- 'SECOND COLUMN NEW NAME'
df
# Rename all at once with a vector
colnames(df3) <- c('col.name.1', 'col.name.2', 'newcol', 'copy.of.col2' ,'col1.times.2')
df3

col.name.1 SECOND COLUMN NEW NAME col1.times.2 copy.of.col2
1          1                      a            2            a
2          2                      b            4            b
3          3                      c            6            c

col.name.1 col.name.2 newcol copy.of.col2 col1.times.2
1          1          a      2            a            1
2          2          b      4            b            2
3          3          c      6            c            3

In [56]:
first.ten.rows <- df[1:10, ] # Same as head(df, 10)
first.ten.rows
everything.but.row.two <- df[-2, ]
everything.but.row.two

col.name.1 SECOND COLUMN NEW NAME col1.times.2 copy.of.col2
1             1                      a            2            a
2             2                      b            4            b
3             3                      c            6            c
NA           NA                   <NA>           NA         <NA>
NA.1         NA                   <NA>           NA         <NA>
NA.2         NA                   <NA>           NA         <NA>
NA.3         NA                   <NA>           NA         <NA>
NA.4         NA                   <NA>           NA         <NA>
NA.5         NA                   <NA>           NA         <NA>
NA.6         NA                   <NA>           NA         <NA>

col.name.1 SECOND COLUMN NEW NAME col1.times.2 copy.of.col2
1          1                      a            2            a
3          3                      c            6            c

In [57]:
sub1 <- df[ (df$col.name.1 > 8 & df$col1.times.2 > 10), ]
sub1

[1] col.name.1             SECOND COLUMN NEW NAME col1.times.2          
[4] copy.of.col2          
<0 rows> (or 0-length row.names)

In [58]:
df[, c(1, 2, 3)] #Grab cols 1 2 3
df[, c('col.name.1', 'col1.times.2')] # by name
df[, -1] # keep all but first column
df[, -c(1, 3)] # drop cols 1 and 3

col.name.1 SECOND COLUMN NEW NAME col1.times.2
1          1                      a            2
2          2                      b            4
3          3                      c            6

col.name.1 col1.times.2
1          1            2
2          2            4
3          3            6

SECOND COLUMN NEW NAME col1.times.2 copy.of.col2
1                      a            2            a
2                      b            4            b
3                      c            6            c

SECOND COLUMN NEW NAME copy.of.col2
1                      a            a
2                      b            b
3                      c            c